In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\rojam\OneDrive\Desktop\projects\climate_risk\Climate_Risk_and_Business_Impact_Dataset.csv")

In [3]:
df.head()

,Business_ID,Business_Name,Industry,Country,State_Province,City,Event_Date,Year,Climate_Event,Severity,...,Vulnerability_Score,Risk_Score,Risk_Level,Downtime_Days,Revenue_Loss_USD,Property_Damage_USD,Supply_Chain_Disruption,Employees_Affected,Recovery_Days,Risk_Mitigation_Investment_USD
0,B0001,ENER_0001,Energy,India,West Bengal,Kolkata,2020-09-06,2020,Cyclone,Critical,...,78.36,69,High,28,1390409.70,997622.50,High,185,49,89105.53
1,B0002,TRAN_0002,Transportation,India,Andhra Pradesh,Visakhapatnam,2020-04-18,2020,Storm,High,...,61.05,74,High,20,1177179.97,686667.50,High,212,38,166823.26
2,B0003,AGRI_0003,Agriculture,Australia,Victoria,Melbourne,2020-06-23,2020,Heatwave,Medium,...,54.18,54,Medium,20,1132973.14,314635.99,Medium,161,46,149976.56
3,B0004,RETA_0004,Retail,United States,California,Los Angeles,2021-10-23,2021,Wildfire,Low,...,36.96,50,Medium,6,641228.66,369725.67,Medium,92,11,92817.74
4,B0005,TRAN_0005,Transportation,Japan,Osaka,Osaka,2025-04-17,2025,Drought,Medium,...,75.05,68,High,10,1002082.16,488002.92,High,187,15,147892.03

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Business_ID                     1000 non-null   object
 1   Business_Name                   1000 non-null   object
 2   Industry                        1000 non-null   object
 3   Country                         1000 non-null   object
 4   State_Province                  1000 non-null   object
 5   City                            1000 non-null   object
 6   Event_Date                      1000 non-null   object
 7   Year                            1000 non-null   int64
 8   Climate_Event                   1000 non-null   object
 9   Severity                        1000 non-null   object
 10  Temperature_Change_C            1000 non-null   float64
 11  Rainfall_Deviation_Percent      1000 non-null   float64
 12  Exposure_Score                  1000 non-null   float64
 13  Vulnerability_Score             1000 non-null   float64
 14  Risk_Score                      1000 non-null   int64
 15  Risk_Level                      1000 non-null   object
 16  Downtime_Days                   1000 non-null   int64
 17  Revenue_Loss_USD                1000 non-null   float64
 18  Property_Damage_USD             1000 non-null   float64
 19  Supply_Chain_Disruption         1000 non-null   object
 20  Employees_Affected              1000 non-null   int64
 21  Recovery_Days                   1000 non-null   int64
 22  Risk_Mitigation_Investment_USD  1000 non-null   float64
dtypes: float64(7), int64(5), object(11)
memory usage: 179.8+ KB

In [5]:
df.shape

(1000, 23)

In [6]:
df.isnull().sum()

Business_ID                       0
Business_Name                     0
Industry                          0
Country                           0
State_Province                    0
City                              0
Event_Date                        0
Year                              0
Climate_Event                     0
Severity                          0
Temperature_Change_C              0
Rainfall_Deviation_Percent        0
Exposure_Score                    0
Vulnerability_Score               0
Risk_Score                        0
Risk_Level                        0
Downtime_Days                     0
Revenue_Loss_USD                  0
Property_Damage_USD               0
Supply_Chain_Disruption           0
Employees_Affected                0
Recovery_Days                     0
Risk_Mitigation_Investment_USD    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [10]:
# Convert the date column
df['Event_Date']=pd.to_datetime(df['Event_Date'])

In [14]:
df.dtypes

Business_ID                               object
Business_Name                             object
Industry                                  object
Country                                   object
State_Province                            object
City                                      object
Event_Date                        datetime64[ns]
Year                                       int64
Climate_Event                             object
Severity                                  object
Temperature_Change_C                     float64
Rainfall_Deviation_Percent               float64
Exposure_Score                           float64
Vulnerability_Score                      float64
Risk_Score                                 int64
Risk_Level                                object
Downtime_Days                              int64
Revenue_Loss_USD                         float64
Property_Damage_USD                      float64
Supply_Chain_Disruption                   object
Employees_Affected                         int64
Recovery_Days                              int64
Risk_Mitigation_Investment_USD           float64
dtype: object

In [12]:
df.describe()

,Event_Date,Year,Temperature_Change_C,Rainfall_Deviation_Percent,Exposure_Score,Vulnerability_Score,Risk_Score,Downtime_Days,Revenue_Loss_USD,Property_Damage_USD,Employees_Affected,Recovery_Days,Risk_Mitigation_Investment_USD
count,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.00000,1000.000000
mean,2023-05-19 10:29:16.800000,2022.899000,1.773100,3.409870,70.375250,65.321730,67.033000,15.323000,9.844948e+05,4.407157e+05,173.915000,32.03400,104410.368350
min,2020-01-01 00:00:00,2020.000000,0.040000,-79.450000,30.800000,26.260000,24.000000,1.000000,1.265477e+05,0.000000e+00,5.000000,1.00000,8823.830000
25%,2021-08-21 06:00:00,2021.000000,1.367500,-14.965000,62.167500,55.340000,58.750000,11.000000,7.554732e+05,2.536833e+05,127.000000,22.00000,60055.155000
50%,2023-05-15 12:00:00,2023.000000,1.780000,2.135000,70.430000,65.595000,67.000000,15.000000,9.925020e+05,4.045280e+05,176.000000,31.00000,94472.675000
75%,2025-01-25 06:00:00,2025.000000,2.190000,22.090000,78.682500,75.002500,76.000000,19.000000,1.197916e+06,5.771549e+05,218.000000,41.00000,143689.745000
max,2026-12-16 00:00:00,2026.000000,3.560000,84.370000,100.000000,100.000000,100.000000,35.000000,1.908411e+06,1.782488e+06,358.000000,74.00000,308081.050000
std,NaN,1.963327,0.586119,27.012838,12.582614,14.149257,12.646654,6.536467,3.150017e+05,2.595355e+05,63.028139,13.82179,56909.958951

In [13]:
df.describe(include='object')

,Business_ID,Business_Name,Industry,Country,State_Province,City,Climate_Event,Severity,Risk_Level,Supply_Chain_Disruption
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,1000,1000,10,6,20,20,6,4,4,3
top,B0001,ENER_0001,Energy,Brazil,Aichi,Nagoya,Cyclone,Medium,High,High
freq,1,1,112,182,68,68,173,372,538,545

In [16]:
numerical_columns=df.select_dtypes(include=['int64','float64']).columns
numerical_columns

Index(['Year', 'Temperature_Change_C', 'Rainfall_Deviation_Percent',
       'Exposure_Score', 'Vulnerability_Score', 'Risk_Score', 'Downtime_Days',
       'Revenue_Loss_USD', 'Property_Damage_USD', 'Employees_Affected',
       'Recovery_Days', 'Risk_Mitigation_Investment_USD'],
      dtype='object')

In [17]:
outlier_columns = [
    'Risk_Score',
    'Downtime_Days',
    'Revenue_Loss_USD',
    'Property_Damage_USD',
    'Employees_Affected',
    'Recovery_Days',
    'Risk_Mitigation_Investment_USD'
]

for column in outlier_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]

    print(f"{column}: {len(outliers)} outliers")

Risk_Score: 2 outliers
Downtime_Days: 9 outliers
Revenue_Loss_USD: 3 outliers
Property_Damage_USD: 19 outliers
Employees_Affected: 1 outliers
Recovery_Days: 5 outliers
Risk_Mitigation_Investment_USD: 4 outliers